name: Build and Release JARs

on:
  pull_request:
    branches:
      - main

jobs:
  build_terminal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Terminal JAR
        run: |
          mkdir -p jar/TicTacToeTerminal
          javac -d jar/TicTacToeTerminal -cp . src/main/java/TTT/TTT.java src/main/java/TTT/Main.java
          echo "Main-Class: TTT.Main" > jar/TicTacToeTerminal/manifest.txt
          jar cfm jar/TicTacToeTerminal/TicTacToeTerminal.jar jar/TicTacToeTerminal/manifest.txt -C jar/TicTacToeTerminal .

      - name: Upload Terminal JAR
        uses: actions/upload-artifact@v2
        with:
          name: Terminal-Release
          path: jar/TicTacToeTerminal/TicTacToeTerminal.jar

  build_gui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build GUI JAR
        run: |
          mkdir -p jar/TicTacToeGUI
          javac -d jar/TicTacToeGUI -cp . src/main/java/TTTSwing/TTTSwing.java src/main/java/TTTSwing/SwingMain.java
          echo "Main-Class: TTTSwing.SwingMain" > jar/TicTacToeGUI/manifest.txt
          jar cfm jar/TicTacToeGUI/TicTacToeGUI.jar jar/TicTacToeGUI/manifest.txt -C jar/TicTacToeGUI .

      - name: Upload GUI JAR
        uses: actions/upload-artifact@v2
        with:
          name: GUI-Release
          path: jar/TicTacToeGUI/TicTacToeGUI.jar

  release:
    runs-on: ubuntu-latest

    needs:
      - build_terminal
      - build_gui

    steps:
      - name: Download Terminal JAR
        uses: actions/download-artifact@v2
        with:
          name: Terminal-Release
          path: jar/TicTacToeTerminal

      - name: Download GUI JAR
        uses: actions/download-artifact@v2
        with:
          name: GUI-Release
          path: jar/TicTacToeGUI
