name: Build and Release JARs

on:
  pull_request:
    branches:
      - main

jobs:
  build_terminal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Terminal JAR
        run: |
          mkdir -p jar/TicTacToeTerminal
          javac -d jar/TicTacToeTerminal -cp . src/main/java/TTT/TTT.java src/main/java/TTT/Main.java
          echo "Main-Class: TTT.Main" > jar/TicTacToeTerminal/manifest.txt
          jar cfm jar/TicTacToeTerminal/TicTacToeTerminal.jar jar/TicTacToeTerminal/manifest.txt -C jar/TicTacToeTerminal .

      - name: List Terminal JAR contents
        run: ls -R jar/TicTacToeTerminal

      - name: Create Terminal Start Script
        run: |
          touch jar/TicTacToeTerminal/start_terminal.sh
          echo '#!/bin/bash' > jar/TicTacToeTerminal/start_terminal.sh
          echo "sudo java -jar TicTacToeTerminal.jar" >> jar/TicTacToeTerminal/start_terminal.sh
          chmod +x jar/TicTacToeTerminal/start_terminal.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.email jai.singh29192@gmail.com
          git config --global user.name thedizzle69
          git add jar/TicTacToeTerminal/
          git commit -m "Created terminal jar"
          git push origin HEAD:Main


      - name: Upload Terminal Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Terminal-Release
          path: jar/TicTacToeTerminal

      - name: Download Terminal JAR and Start Script
        uses: actions/download-artifact@v2
        with:
          name: Terminal-Release
          path: jar/TicTacToeTerminal

  build_gui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build GUI JAR
        run: |
          mkdir -p jar/TicTacToeGUI
          javac -d jar/TicTacToeGUI -cp . src/main/java/TTTSwing/TTTSwing.java src/main/java/TTTSwing/SwingMain.java
          echo "Main-Class: TTTSwing.SwingMain" > jar/TicTacToeGUI/manifest.txt
          jar cfm jar/TicTacToeGUI/TicTacToeGUI.jar jar/TicTacToeGUI/manifest.txt -C jar/TicTacToeGUI .
          

      - name: List GUI JAR contents
        run: ls -R jar/TicTacToeGUI

      - name: Create GUI Start Script
        run: |
          touch jar/TicTacToeGUI/start_gui.sh
          echo '#!/bin/bash' > jar/TicTacToeGUI/start_gui.sh
          echo "java -jar TicTacToeGUI.jar" >> jar/TicTacToeGUI/start_gui.sh
          chmod +x jar/TicTacToeGUI/start_gui.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.email jai.singh29192@gmail.com
          git config --global user.name thedizzle69
          git add jar/TicTacToeGUI/
          git commit -m "Created GUI jar"
          git push origin HEAD:main

      - name: Upload GUI JAR
        uses: actions/upload-artifact@v2
        with:
          name: GUI-Release
          path: jar/TicTacToeGUI

      - name: Download GUI JAR and Start Script
        uses: actions/download-artifact@v2
        with:
          name: GUI-Release
          path: jar/TicTacToeGUI

  release:
    runs-on: ubuntu-latest

    needs:
      - build_terminal
      - build_gui

    steps:
      - name: Download Terminal JAR and Start Script
        uses: actions/download-artifact@v2
        with:
          name: Terminal-Release
          path: jar/TicTacToeTerminal

      - name: Download GUI JAR and Start Script
        uses: actions/download-artifact@v2
        with:
          name: GUI-Release
          path: jar/TicTacToeGUI


