name: Checkdiz

on:
  push:
    branches:
      - '*'

jobs:
  checkdiz:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Run Checkstyle
      run: mvn checkstyle:check
