name: Generate and Deploy Javadoc

on:
  pull_request:
    branches:
      - main

jobs:
  generate_javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Move Javadoc to Directory
        run: mv target/site/apidocs/* docs/

      - name: Upload Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs
          github_token: ${{ secrets.DOC_TOKEN }}
          publish_branch: main